# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6121befb34b6a68a0e0f623ee6840ad612d3d9f6deae62731cbbfb608d10802e8c2225a4e8e5392ae7f8fe969c9184f659388eaa94212883f27f63b062842751

test:
  secret_key_base: 96c8587dd88c8f73da706d331e6305a1e5b8301192c73d3bb9653bedea1fe35a4a4127ddbb27125ea5439fb445e79ddddca266838f8893601b553db2a98844fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
